language: node_js

matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode8.3
node_js:
  - "6"
script:
  - pushd web && npm install && npm run build && popd
  - pushd web && npm install && npm run electron && popd
  - pushd electron && npm install && npm run release && popd

