language: node_js
node_js: 7
branches:
  only:
    - rudex
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode8.3
env:
  global:
  - GITHUB_REPO: bitshares/bitshares-ui
  - ORGANIZATION_REPO: bitshares/rudex.org
  - WALLET_REPO: bitshares/market.rudex.org
  - CXX=g++-4.8
  - secure: "KhSBX62FS4IQiaOKuPEKhTsFpzcClTo2kcGlPdHvqScjLX7vzvrGkygT97+3pxyJotKNQdxid5ewOXnRMi6lIpr8NOGx+4QWL6Itd5BS6xiWsKv/3PQcdGhRiYjMd2tDQaa6cg0k3uh8UJAoX5/v7cSC+VxrWnD3UjD3N/gtb/sYKDvFBTI3//OfRJjyGofA1RiwpT1KNrWMtqIJ98laTeu6xFydeq8BYA30jzQk41nZE10ZdIJQ72s8rzauDvdTbzlcBCdhnDiCtjjKyvLSGgGtL9FkNQLXPKtlk/ywquqi70P1u5SLwh6Ssq+aGsLjIDPBl1UZkC+GhYXijcWkNtlo5X19pn0ZksHSzQSmnrgBMB2hVJX98761eoLMFUXopFkB3Ye47WETnn0RjP5ZKwDD61338y+qpYcWW8h69xeWzvqT5a8+eOEU1hc7k9A8AjnFfb+sbs8kLEVO7bbDpHnXli+edzbkLw/3+evkevTUphBHtdBPAVUVJ9ZKputkrt8z1s5V+V4O2rB9BCky6NpIMGi+RUS2sDoDd2Ys4X9XyN/WCOoh+AwY8iLlmNUSk4SbxZSm5ZvRvbv5cZ9157MIbaoTZTGzDfsedsQMJ4xE6U2z1/61EdZWg9Rg9nFdtzIxORWT17MLlfvhX5qXIBxhTeNF3JzLWpxkYCUg1/A="
cache:
  directories:
    - "node_modules"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - icnsutils
    - graphicsmagick
    - xz-utils
before_install: "./install.sh"
script: "./build.sh"
#after_success: "./deploy.sh"
deploy:
  provider: releases
  tag_name: $TRAVIS_TAG
  name: $TRAVIS_TAG
  body: Automated release from Travis CI with added files from AppVeyor build
  api_key:
    secure: "n+dpQi+eVJRGEEyAySYXOzIjS6ObFvGCGGdY2EhZhIMIB2U2FWIdzzhNBP4xLo2SnFgk9shLvIHHBQ5H5vyHaAICtbwQM5KLAHOXIEYzZ6q3G4/RJiSsNe7X/ZfQZ/cXZVIjOKXM2ZLQtMcV5uLZB3pwW5H2zBAYbPYjLtlIpbe4CI+RuPjVRYHks3Xf0RJifXINFwm4t9DMgV9AH0LD/N635IE1dA9eF4nr2naxSrpOVYgj1LETvZ21A9/cBAzfynB2gbva/ElWLKk07iiuWABSnyjo1dWDhCzcrQkuBGf+L5IkMcmZncN5zpscgzJQzTMYN9RYhvERqvKgc18O9QLaNcG06TlmulHwIGpbA3KNASShhckMq8WvWPQ0cPdLSIvHoql354Lz3CvCCwCdkf3+zGBgz3uA+U8p7seufSDseEFJ2On5kOO8ZsQyG0JBTVzjyQfh0EbNaxo40ZiZZTONP+C+TIS7owpVTS/2Ask7nNW7bWw9aQ61h82ub7IeCXoH2ouRRMDmikxMbRm254sEqnpCyaKO9XwApVFjgJn4mP8s7URxyVcLnMvfVmjkBJCSwmka0y1Z00oC2W4/FP3WsbIOelIQ+8Ew1M4YOoFC402H/XiQyW47Dm58UxzSZavRJMnUx5uCphxoKUUdkD+lMwB2K/4AaQFQM3GnJ9U="
  file_glob: true
  file: "build/binaries/*.{dmg,deb}"
  overwrite: true
  skip_cleanup: true
  draft: true
  on:
    repo: blckchnd/rudex-ui
    tags: true
